In [1]:
import pandas as pd
import numpy as np

In [2]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        0.734, 
        0.724, 
        0.766, 
        0.794
    ],
    "Precision": [
        0.499, 
        0.487, 
        0.541, 
        0.646
    ],
    "Recall": [
        0.789, 
        0.775, 
        0.770, 
        0.497
    ],
    "F1": [
        0.611, 
        0.598, 
        0.636, 
        0.562
    ],
    "ROC_AUC": [
        0.841, 
        0.827, 
        0.844, 
        0.846
    ]
})

results

                 Model  Accuracy  Precision  Recall     F1  ROC_AUC
0  Logistic Regression     0.734      0.499   0.789  0.611    0.841
1        Decision Tree     0.724      0.487   0.775  0.598    0.827
2        Random Forest     0.766      0.541   0.770  0.636    0.844
3              XGBoost     0.794      0.646   0.497  0.562    0.846

In [3]:
weights = {
    "ROC_AUC": 0.40,
    "Recall": 0.30,
    "F1": 0.20,
    "Precision": 0.10
}

In [4]:
results["Weighted_Score"] = (
    results["ROC_AUC"] * weights["ROC_AUC"] +
    results["Recall"] * weights["Recall"] +
    results["F1"] * weights["F1"] +
    results["Precision"] * weights["Precision"]
)

results.sort_values(by="Weighted_Score", ascending=False)

,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Weighted_Score
2,Random Forest,0.766,0.541,0.770,0.636,0.844,0.7499
0,Logistic Regression,0.734,0.499,0.789,0.611,0.841,0.7452
1,Decision Tree,0.724,0.487,0.775,0.598,0.827,0.7316
3,XGBoost,0.794,0.646,0.497,0.562,0.846,0.6645

In [5]:
results[["Model", "Weighted_Score"]].sort_values(
    by="Weighted_Score", ascending=False
)

                 Model  Weighted_Score
2        Random Forest          0.7499
0  Logistic Regression          0.7452
1        Decision Tree          0.7316
3              XGBoost          0.6645