In [1]:
import pandas as pd
import numpy as np

In [9]:
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        0.735, 
        0.754, 
        0.764, 
        0.804
    ],
    "Precision": [
        0.501, 
        0.526, 
        0.539, 
        0.674
    ],
    "Recall": [
        0.791, 
        0.751, 
        0.749, 
        0.508
    ],
    "F1": [
        0.613, 
        0.619, 
        0.627, 
        0.579
    ],
    "ROC_AUC": [
        0.841, 
        0.837, 
        0.843, 
        0.848
    ]
})

results

                 Model  Accuracy  Precision  Recall     F1  ROC_AUC
0  Logistic Regression     0.735      0.501   0.791  0.613    0.841
1        Decision Tree     0.754      0.526   0.751  0.619    0.837
2        Random Forest     0.764      0.539   0.749  0.627    0.843
3              XGBoost     0.804      0.674   0.508  0.579    0.848

In [10]:
weights = {
    "ROC_AUC": 0.40,
    "Recall": 0.30,
    "F1": 0.20,
    "Precision": 0.10
}

In [11]:
results["Weighted_Score"] = (
    results["ROC_AUC"] * weights["ROC_AUC"] +
    results["Recall"] * weights["Recall"] +
    results["F1"] * weights["F1"] +
    results["Precision"] * weights["Precision"]
)

results.sort_values(by="Weighted_Score", ascending=False)

,Model,Accuracy,Precision,Recall,F1,ROC_AUC,Weighted_Score
0,Logistic Regression,0.735,0.501,0.791,0.613,0.841,0.7464
2,Random Forest,0.764,0.539,0.749,0.627,0.843,0.7412
1,Decision Tree,0.754,0.526,0.751,0.619,0.837,0.7365
3,XGBoost,0.804,0.674,0.508,0.579,0.848,0.6748

In [12]:
results[["Model", "Weighted_Score"]].sort_values(
    by="Weighted_Score", ascending=False
)

                 Model  Weighted_Score
0  Logistic Regression          0.7464
2        Random Forest          0.7412
1        Decision Tree          0.7365
3              XGBoost          0.6748